project_name: go-testing-framework
builds:
  - env: [CGO_ENABLED=0]
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
nfpms:
- maintainer: Brandon Cate
  description: Sample project.
  homepage: https://github.com/caarlos0/tasktimer
  license: MIT
  formats:
  - deb
  - rpm
  - apk