project_name: go-testing-framework
builds:
  - env: [CGO_ENABLED=0]
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
# .goreleaser.yml
scoop:
  commit_author:
    name: goreleaserbot
    email: goreleaser@carlosbecker.com
  commit_msg_template: "Scoop update for {{ .ProjectName }} version {{ .Tag }}"
  homepage: http://thedummydogo.com/
  description: "Software to create fast and easy drum rolls."
  license: MIT
nfpms:
- maintainer: Brandon Cate
  description: Sample project.
  homepage: http://thedummydogo.com/
  license: MIT
  formats:
  - deb
  - rpm
  - apk